[package]
name = "teleop_twist_keyboard_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r2r = "0.8.3"
termios = "0.3.3"
lazy_static = "1.4"